name: wallpaper_sync_plugin
description: Internal plugin that exposes native wallpaper-setting capabilities for Twain.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.judahben149.wallpaper_sync_plugin
        pluginClass: WallpaperSyncPlugin

dependencies:
  flutter:
    sdk: flutter

